version: '3'

services:
    db:
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: hello
            MYSQL_DATABASE: db
            MYSQL_USER: app_user
            MYSQL_PASSWORD: helloworld
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony
        depends_on:
            - db
        hostname: app_php
        restart: always
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 80:80
        networks:
            - symfony
        depends_on:
            - db
        hostname: app_nginx
        restart: always

volumes:
    db_app:

networks:
    symfony: